#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

if [[ $(xrandr -q | grep 'DP-3 connected') ]]; then
    xrandr  --output eDP-1 --primary --mode 1920x1080 --rotate normal \
            --output DP-3 --mode 3200x1800 --rotate normal --left-of eDP-1
fi

bspc monitor DP-3 -d 6 7 8 9 0
bspc monitor eDP-1 -d 1 2 3 4 5


$HOME/.config/polybar/launch.sh
